site_name: HIKVISION 기술 지원 센터

theme:
  name: material
  language: ko
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs  # 메뉴를 상단 탭으로 보여줍니다

nav:
  - 홈: index.md
  - 🔍 비밀번호 초기화 방법:
      - NVR 초기 설정: 녹화기/setup.md
      - 비밀번호 찾기: 녹화기/password.md
      - 재생하기 : 녹화기/재생.md
  - 🔍 Hik-Connect (어플) 사용 방법:
      - IP 카메라 연결: camera/connect.md
  - 🔍 NVR & IP 카메라 설정 방법:
      - 유튜브 가이드: video.md
  - 🔍 iVMS- 4200 사용 방법:
      - 유튜브 가이드: video.md
  - 🔍기능 설정 방법:
      - 유튜브 가이드: video.md
  - 🔍설치업자를 위한 Hik-Partner Pro 사용 방법:
      - 유튜브 가이드: video.md